<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>Veyro</AssemblyName>
    <RootNamespace>Veyro.Desktop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Veyro.Desktop.Core/Veyro.Desktop.Core.csproj" />
    <Resource Include="Assets/veyro_logo_color.png" />
  </ItemGroup>
</Project>
